language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn test
deploy:
  provider: npm
  email: joel@oblador.se
  api_key:
    secure: "KETX2hAy9M6jDWctTKZX7osMzvkH3goD3dmoK9x+s0UnUEDmppk1Qoj+HP3rDs5foLBP7bXdFKsMxBo91MFy+816c5+rAcR7y6mIaaHIcfsTB2sxFwAL43ikJ9hffb58IrgqHPr0Ns64e6CUXqGe60F1CADLoDfYl2Yd3HZOuKLVlBqCEqLuHAFVPB7ollhFgnhhEOJKr2BaxqbUJmvgSHuqdLwwmj9O2/1sADhLI2iF/rnEDDlKiHM1mzkfcvbUKsAKyElCvzRhTAsbyBfzstpen28ln2HIEGi4mNsWdvXENyFIxv2UMKque/d0PQR/A+axrn+O4vrXNUAcPe1qcQfITYH8MbM92iPdFmpFarQGV+lAsE0Uy+7OHKYe4/oHHvIE7S3qsZEesZWFc4MUacaE9FbrtxV6YYmVAo+fN5Cq2iFCerr/jiZTfusq9Txmj3PX7+IImeYAk4ssCxTUtkgMgacSDT1626zect71SpJZy1a/QrwHYs28gd97vfGs6UsZGWge/ogS3IUrnJ5fxFlv90+Y/q8ntAdbCa7HUYXEmkFPN9CeOaom31DbbWhjgBK0uUrCrq56cM3adFlHl60plIB/72kQPsTgHOIu1Ei3jZp8MFdhOnK+KJlflhZNi5+3p3u0UOX5flvlx8WCy/a4YEUAa8m7ma43V8JKfNI="
  on:
    tags: true
    repo: kictech/react-native-progress
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+.*$"
